[versions]
# kotlin = "1.4.32"
ksp = "1.4.32-1.0.0-alpha07"
compose = "1.0.0-beta07"
androidx_activity = "1.3.0-alpha08"
accompanist = "0.10.0"
retrofit2 = "2.9.0"
hilt = "2.35.1"
androidx_hilt = "1.0.0"
room = "2.4.0-alpha02"
lifecycle_base = "2.4.0-alpha01"
lifecycle_compose = "1.0.0-alpha05"
okhttp = "4.9.1"
kotlinx_serialization = "1.2.0"
paging_base = "3.0.0"
paging_compose = "1.0.0-alpha09"
ktlint = "0.41.0"
protobuf = "3.17.0"
work = "2.7.0-alpha03"
dataStore = "1.0.0-beta01"
exoplayer = "2.14.0"
androidx_test = "1.4.0-alpha05"
extJUnitVersion = "1.1.3-alpha05"
espressoVersion = "3.4.0-alpha05"
startup = "1.1.0-beta01"
kotlin-coroutines = "1.5.0"

[libraries]
# androidx test
androidx-test-core = {module = "androidx.test:core", version.ref = "androidx_test"}
androidx-test-runner = {module = "androidx.test:runner", version.ref = "androidx_test"}
androidx-test-ext-junit = {module = "androidx.test.ext:junit", version.ref = "extJUnitVersion"}
androidx-test-espresso = {module = "androidx.test.espresso:espresso-core", version.ref = "espressoVersion"}

mockito-core-test = 'org.mockito:mockito-core:3.8.0'
mockito-kotlin-test = 'org.mockito.kotlin:mockito-kotlin:3.1.0'
android-test-core = 'android.arch.core:core-testing:1.1.1'


# Compose
compose-ui-base = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-ui-test = { module = "androidx.compose.ui:ui-test", version.ref = "compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
compose-animation = { module = "androidx.compose.animation:animation", version.ref = "compose" }
compose-material-base = { module = "androidx.compose.material:material", version.ref = "compose" }
compose-material-icons-core = { module = "androidx.compose.material:material-icons-core", version.ref = "compose" }
compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "compose" }
compose-runtime_livedata = { module = "androidx.compose.runtime:runtime-livedata", version.ref = "compose" }

# Paging
paging-runtime = { module = "androidx.paging:paging-runtime-ktx", version.ref = "paging_base" }
paging-compose = { module = "androidx.paging:paging-compose", version.ref = "paging_compose" }

# Lifecycle
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle_base" }
lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle_base" }
lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle_base" }
lifecycle-viewmodel-savedstate = { module = "androidx.lifecycle:lifecycle-viewmodel-savedstate", version.ref = "lifecycle_base" }
lifecycle-common-java8 = { module = "androidx.lifecycle:lifecycle-common-java8", version.ref = "lifecycle_base" }
lifecycle-viewmodel-compose_compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle_compose" }

# Room
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-testing = { module = "androidx.room:room-testing", version.ref = "room" }

# Hilt
hilt-android-base = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-work = { module = "androidx.hilt:hilt-work", version.ref = "androidx_hilt" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
hilt-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "androidx_hilt" }

# Accompanist
accompanist-coil = { module = "com.google.accompanist:accompanist-coil", version.ref = "accompanist" }
accompanist-insets = { module = "com.google.accompanist:accompanist-insets", version.ref = "accompanist" }
accompanist-pager-base = { module = "com.google.accompanist:accompanist-pager", version.ref = "accompanist" }
accompanist-pager-indicators = { module = "com.google.accompanist:accompanist-pager-indicators", version.ref = "accompanist" }

# AndroidX Activity
activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "androidx_activity" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx_activity" }

# DataStore
dataStore = { module = "androidx.datastore:datastore", version.ref = "dataStore" }

# WorkManager
work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "work" }

# Kotlinx Serialization
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx_serialization" }

# Kotlinx Coroutines
kotlinx-coroutines-core = {module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlin-coroutines"}
kotlinx-coroutines-test = {module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlin-coroutines"}

# Retrofit
retrofit-base = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit2" }
retrofit-converter-scalars = { module = "com.squareup.retrofit2:converter-scalars", version.ref = "retrofit2" }
retrofit2-kotlinx-serialization-converter = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter:0.8.0"

# OkHttp
okhttp-base = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-logging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }

# KSP
ksp-symbol-processing-api = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }

zoomable = "com.github.Tlaster:Zoomable:0.5.0"
nestedScrollView = "com.github.Tlaster:NestedScrollView:0.4.0"
swiper = "com.github.Tlaster:Swiper:0.3.0"
placeholder = "com.github.Tlaster:Placeholder:0.4.0"
twittertext = "com.twitter.twittertext:twitter-text:3.1.0"
jsoup = "org.jsoup:jsoup:1.13.1"
leakcanary = "com.squareup.leakcanary:leakcanary-android:2.7"
protobuf-javalite = { module = "com.google.protobuf:protobuf-javalite", version.ref = "protobuf" }
exoplayer = { module = "com.google.android.exoplayer:exoplayer", version.ref = "exoplayer" }
startup = { module = "androidx.startup:startup-runtime", version.ref = "startup" }
vectordrawable = "androidx.vectordrawable:vectordrawable:1.1.0"

[bundles]
androidx-test = [
    "androidx-test-core",
    "androidx-test-runner",
    "androidx-test-ext-junit",
    "androidx-test-espresso",
]

mockito-test = [
    "mockito-core-test",
    "mockito-kotlin-test"
]

compose = [
    "compose-ui-base",
    "compose-ui-tooling",
    "compose-foundation",
    "compose-animation",
    "compose-material-base",
    "compose-material-icons-core",
    "compose-material-icons-extended",
    "compose-runtime_livedata",
]
paging = [
    "paging-runtime",
    "paging-compose",
]
lifecycle = [
    "lifecycle-runtime-ktx",
    "lifecycle-viewmodel-ktx",
    "lifecycle-livedata-ktx",
    "lifecycle-viewmodel-savedstate",
    "lifecycle-common-java8",
    "lifecycle-viewmodel-compose_compose",
]
room = [
    "room-runtime",
    "room-ktx",
]
hilt-base = [
    "hilt-android-base",
    "hilt-work",
]
hilt-compiler = [
    "hilt-android-compiler",
    "hilt-compiler",
]
accompanist = [
    "accompanist-coil",
    "accompanist-insets",
    "accompanist-pager-base",
    "accompanist-pager-indicators",
]
activity = [
    "activity-ktx",
    "activity-compose",
]
okhttp = [
    "okhttp-base",
    "okhttp-logging",
]
retrofit = [
    "retrofit-base",
    "retrofit-converter-scalars",
]